// <auto-generated />
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace photogrph_Displayer_api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20201029234850_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Model.Photographer", b =>
                {
                    b.Property<int>("PhotographerId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePictureName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PhotographerId", "Email");

                    b.ToTable("Photographer");
                });

            modelBuilder.Entity("Model.Photos", b =>
                {
                    b.Property<string>("PhotographerEmail")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PhotosId")
                        .HasColumnType("int");

                    b.Property<string>("PhotosName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PhotographerEmail", "PhotosId");

                    b.ToTable("Photos");
                });
#pragma warning restore 612, 618
        }
    }
}
